package com.decom.entity;

import java.util.Date;

public class Appointment {
    private long bookId;// 图书ID
    private long studentId;// 学号
    private Date appointTime;
    //多对一复合属性
    private Book bookEntity;

    /**
     * DaiH 2017-9-25 添加默认构造函数，以解决
     * org.apache.ibatis.executor.ExecutorException: No constructor found in 包名.类名.
     * 这个错误的产生是mybatis查询语句返回的结果中由Integer等基本类型与构造函数中的int等类型转换的问题.
     *  mybatis：
     *  mybatis高级映射需要进一步学习
     */
    public Appointment() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbggenerated
     */
    public Appointment(Long bookId, Long studentId, Date appointTime) {
        this.bookId = bookId;
        this.studentId = studentId;
        this.appointTime = appointTime;
    }

    public Appointment(long bookId, long studentId, Date appointTime, Book bookEntity) {
        this.bookId = bookId;
        this.studentId = studentId;
        this.appointTime = appointTime;
        this.bookEntity = bookEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appoint_time
     *
     * @return the value of appointment.appoint_time
     *
     * @mbggenerated
     */
    public Date getAppointTime() {
        return appointTime;
    }

    public long getBookId() {
        return bookId;
    }

    public long getStudentId() {
        return studentId;
    }

    public Book getBook() {
        return bookEntity;
    }

    public void setBookId(long bookId) {
        this.bookId = bookId;
    }

    public void setStudentId(long studentId) {
        this.studentId = studentId;
    }

    public void setAppointTime(Date appointTime) {
        this.appointTime = appointTime;
    }

    public void setBook(Book book) {
        this.bookEntity = book;
    }
}